name: movingPictures
description: Real-world movie database mobile application with the Flutter SDK
  and DDD clean architecture.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  auto_route: ^0.6.9
  bloc: ^6.1.0
  cloud_firestore: ^0.14.3
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  equatable: ^1.2.5
  firebase_auth: ^0.18.3
  firebase_core: ^0.5.2
  flushbar: ^1.10.4
  flutter_bloc: ^6.1.1
  flutter_svg: ^0.19.1
  freezed_annotation: null
  get_it: ^5.0.1
  google_sign_in: ^4.5.6
  injectable: ^1.0.5
  json_annotation: ^3.1.0
  shimmer: ^1.1.2
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: null
  auto_route_generator: ^0.6.10
  build_runner: null
  flutter_launcher_icons: ^0.8.1
  freezed: null
  injectable_generator: ^1.0.6
  json_serializable: ^3.5.0
  lint: ^1.3.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/moving_pictures_logo_man.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/icons/regularIcons/
    - assets/icons/numberIcons/
    - lang/
    

  fonts:
    - family: Montez
      fonts:
        - asset: fonts/Montez/Montez-Regular.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Light.ttf
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
