name: movingPictures
description: Real-world movie database mobile application with the Flutter SDK
  and DDD clean architecture.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.9
  bloc: ^6.1.0
  cloud_firestore: ^0.14.2
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  equatable: ^1.2.5
  firebase_auth: ^0.18.2
  firebase_core: ^0.5.1
  flushbar: ^1.10.4
  flutter_bloc: ^6.0.6
  freezed_annotation: 
  get_it: ^5.0.1
  google_sign_in: ^4.5.5
  injectable: ^1.0.5
  json_annotation: ^3.1.0
  uuid: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.10
  build_runner:
  freezed: 

  analyzer:
  injectable_generator: ^1.0.6
  json_serializable: ^3.5.0
  lint: ^1.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/Montserrat-Light.ttf
        - asset: fonts/Montserrat/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Light.ttf
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Medium.ttf
          weight: 500
